gitprint("******************************************")
print("*    Primera Practica Ingenieria de      *")
print("*                Software                *")
print("*             Lista de Tareas            *")
print("******************************************\n")

print("Integrantes:")
print("- Rosario Calisaya")
print("- Ignacio Tapia")
print("- Willy Vargas")
